### ISSUE TITLE
set accet header in queries to SPARQL endpoint

### ISSUE THREAD

**Issue by pchampin** [Wimmics/voidmatic#1]
Nice project! :)

I detected a small bug, when trying to extract metadata from the endpoint:
- voidmatic sends the SPARQL query with `accept: */*`
- but it expects results in the JSON format,
- so if the server sends another formats, voidmatic crashes.

Solution: specify `accept: application/sparql-results+json`

**Comment by MaillPierre** [comment]
Do you have a sparql endpoint in this case for testing purposes ?

**Comment by pchampin** [comment]
It is not a public one, but it is based on GraphDB (which seems to 
returns CSV by default).

**Comment by MaillPierre** [comment]
The modification has been done.
