### ISSUE TITLE
Invalid xsd:dateTime literals produced

### ISSUE THREAD

**Issue by jmkeil** [Wimmics/voidmatic#11]
Hi. The tool produces invalid [xsd:dateTime](https://www.w3.org/TR/xmlschema11-2/#dateTime) literals. For example, `"2018-02-12"^^xsd:dateTime` is invalid. Better use [xsd:date](https://www.w3.org/TR/xmlschema11-2/#date) and only permit the YYYY-MM-DD pattern. That should be sufficient for the use case.

**Comment by MaillPierre** [comment]
I went a bit too far and now it tries to recognize if the value is a date or a datetime.

**Comment by jmkeil** [comment]
Great. But there are still two problems:
* TimeZone must be in the range `-14:00` to `+14:00`, but currently `-23:59` to `+23:59` is permitted.
* `YYYY-MM` and `YYYY` are recognize as [xsd:string](https://www.w3.org/TR/xmlschema11-2/#string), but better should be recognize as [xsd:gYearMonth](https://www.w3.org/TR/xmlschema11-2/#gYearMonth) and [xsd:gYear](https://www.w3.org/TR/xmlschema11-2/#gYear)

**Comment by MaillPierre** [comment]
Thank you very much for the follow-up.

gYear and gYearMonth are now correctly handled.
Concerning the timezone, as I delegate the date format checking to the dayjs library, I do not plan to code something to check the datetime format in detail, so I will not correct this behavior for now.

Thank you for the tickets.
