### ISSUE TITLE
number of triples taking too long

### ISSUE THREAD

**Issue by gatemezing** [Wimmics/voidmatic#13]
Hello @MaillPierre , 
Nice tool! I was trying to test the tool and realize that the query to get the total number of triples was taking too much time. 
When I use the following query, I get the result in a reasonable time 
`
SELECT (count(*) AS ?count) 
{
  ?s ?p ?o  
}
`
Did you experiment it with other types of endpoints? TIA

**Comment by MaillPierre** [comment]
Thank you for the ticket. I don't know why I made the triple count query so complex. I put this one instead.
