### ISSUE TITLE
Language tag not able to be extracted 

### ISSUE THREAD

**Issue by gatemezing** [Wimmics/voidmatic#14]
Hello @MaillPierre,
I have an issue with the query for extracting the language tags.
Maybe it would be good to put a limit 50 in the query? The query can easily hits the timeout for many endpoints.
The query below seems to solve my use case.
`
SELECT DISTINCT ?tag 
WHERE {
    ?s ?p ?o
  FILTER(ISLITERAL(?o))
 BIND (LANG(?o) AS ?tag)    
  } LIMIT 50
`

**Comment by MaillPierre** [comment]
Thank you for the remark, I'm adding a limit to the query as you propose.
