### ISSUE TITLE
Problem with extract functionnality

### ISSUE THREAD

**Issue by datamusee** [Wimmics/voidmatic#2]
I have a public endpoint
https://ws49-cl4-jena.tl.teralab-datascience.fr/SemJoconde/sparql
and each trial was unsuccessful with the message
Error: Could not retrieve the data. Have you tried to force the endpoint URL into HTTPS ?
I've also tried http://ws49-cl4-jena.tl.teralab-datascience.fr/SemJoconde/sparql
and http://ws49-cl4-jena.tl.teralab-datascience.fr/SemJoconde/query

**Comment by MaillPierre** [comment]
It seems the endpoint does not accept "application/json" as the accepted content type, despite returning JSON.
This will be corrected shortly

**Comment by MaillPierre** [comment]
Quick fix is to comment line 65 in index.js in your fork

**Comment by datamusee** [comment]
OK. It works for me
