### ISSUE TITLE
Multiple values for triples, classes, props

### ISSUE THREAD

**Issue by frmichel** [Wimmics/voidmatic#4]
Clicking the Extract button multiple times will create multiple times the triple with the number of triples, classes etc.

Example with https://taxref.mnhn.fr/sparql : 

```
ex:dataset
    void:classes 1652, 1922;
    void:triples 2779906, 3807906;
```

**Comment by MaillPierre** [comment]
We keep the existing value now. The queries have been redone to be more precise, but sometimes the same query will still returns different results at different times. Not sure what to do about that.
Closing the issue about the duplicate lines either way.
